# Generated by Django 5.2.1 on 2026-04-21 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoriterestaurant',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='favoriterestaurant',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_favorite_per_user'),
        ),
        migrations.AddConstraint(
            model_name='favoriterestaurant',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('session_key', 'restaurant'), name='unique_favorite_per_session'),
        ),
    ]
